### ISSUE TITLE
The APK Build

### ISSUE THREAD

**Issue by memreb** [Kloen/citra-android#42]
Hi Kloen,
if you finished your build, please publish it as apk.
I would like to test the app and play 3DS games on android.

Thanks for developing and Good Luck!!

**Comment by Kloen** [comment]
Hi @memreb,

It's not finished yet, as you could see in other Issues, the one that refers to the first Alpha, the development is stopped due I don't have enought time right now due to personal and work issues that doesn't allow me to continue for the time being.

In addition, please, don't open an Issue here, there is no point on that, cause that's not what Issue means.

For questions, please, refer to my mail: kloen@outlawkiwi.com where I try to answer all mails as fast as I can.

Kind regards.

**Comment by memreb** [comment]
Hello Kloen

Oh, ok thanks😀
